import type { Locale } from './identity-copy';
const en = {
  myClasses: 'My Class',
  createSchool: 'Create a school workspace',
  createClass: 'Create a class',
  join: 'Join a class',
  intro: 'A place for your class to begin.',
  empty:
    'Your class story starts here. Create a school workspace, or join with an invitation from your class representative.',
  school: 'School',
  schoolName: 'School name',
  name: 'Class name',
  slug: 'Short address',
  slugHint:
    'Use lowercase letters, numbers and hyphens. This must be unique within its school; school addresses are unique across the platform.',
  location: 'Location (optional)',
  year: 'Graduation year',
  motto: 'Motto (optional)',
  save: 'Save changes',
  create: 'Create',
  back: 'Back to my classes',
  manage: 'Manage',
  members: 'Members',
  invite: 'Create invitation',
  code: 'Invitation code',
  joinIntro:
    'Enter the code your class representative shared. Joining requires your explicit acceptance.',
  accept: 'Accept invitation',
  signIn: 'Sign in to continue',
  register: 'Create an account',
  returnJoin:
    'Sign in or register in the new tab, then return here to accept your invitation.',
  loading: 'Loading…',
  busy: 'Please wait…',
  error: 'We could not complete this request. Please try again.',
  retry: 'Try again',
  invalid:
    'Check the details. An invitation may be expired, revoked or fully used.',
  denied: 'You do not have access to this action or class.',
  conflict:
    'This address is already in use, or the change would leave the class without an administrator.',
  limited: 'Too many attempts. Wait 15 minutes before trying again.',
  previous: 'Previous',
  next: 'Next',
  page: 'Page',
  role: 'Role',
  status: 'Status',
  active: 'Active',
  removed: 'Removed',
  member: 'Member',
  admin: 'Class administrator',
  staff: 'Teacher / staff',
  guest: 'Guest',
  days: 'Expires in days',
  maxUses: 'Maximum uses',
  used: 'Uses',
  expires: 'Expires',
  revoke: 'Revoke invitation',
  revoked: 'Revoked',
  inviteList: 'Invitations',
  inviteEmpty: 'No invitations yet. Invite your classmates when you are ready.',
  share: 'Share this invitation',
  once: 'Save this code or link now. It is shown only once. Share it only with people you want to invite.',
  link: 'Invitation link',
  qr: 'QR code for this invitation link',
  qrError:
    'The QR code could not be generated. You can still use the invitation link.',
  saved: 'Changes saved.',
  private: 'Private class workspace',
  schoolNotice:
    'This creates a private workspace. It does not claim official verification by the school.',
  noSchools: 'Create a school workspace first, then add your graduating class.',
  schoolManage: 'Manage school',
};
export const classCopy: Record<Locale, typeof en> = {
  en,
  ht: {
    myClasses: 'Klas mwen',
    createSchool: 'Kreye yon espas lekòl',
    createClass: 'Kreye yon klas',
    join: 'Antre nan yon klas',
    intro: 'Yon plas pou klas ou kòmanse.',
    empty:
      'Istwa klas ou kòmanse isit la. Kreye yon espas lekòl oswa antre avèk yon envitasyon reprezantan klas ou.',
    school: 'Lekòl',
    schoolName: 'Non lekòl la',
    name: 'Non klas la',
    slug: 'Adrès kout',
    slugHint:
      'Itilize ti lèt, chif ak tirè. Adrès klas la dwe inik nan lekòl la; adrès lekòl yo dwe inik sou platfòm nan.',
    location: 'Kote (opsyonèl)',
    year: 'Ane gradyasyon',
    motto: 'Deviz (opsyonèl)',
    save: 'Anrejistre chanjman yo',
    create: 'Kreye',
    back: 'Retounen nan klas mwen yo',
    manage: 'Jere',
    members: 'Manm yo',
    invite: 'Kreye envitasyon',
    code: 'Kòd envitasyon',
    joinIntro:
      'Antre kòd reprezantan klas ou pataje a. Ou dwe aksepte envitasyon an pou antre.',
    accept: 'Aksepte envitasyon',
    signIn: 'Konekte pou kontinye',
    register: 'Kreye yon kont',
    returnJoin:
      'Konekte oswa enskri nan nouvo onglet la, epi retounen isit la pou aksepte envitasyon ou.',
    loading: 'N ap chaje…',
    busy: 'Tanpri tann…',
    error: 'Nou pa t kapab fini demann sa a. Tanpri eseye ankò.',
    retry: 'Eseye ankò',
    invalid:
      'Tcheke enfòmasyon yo. Envitasyon an ka ekspire, revoke oswa fin itilize.',
    denied: 'Ou pa gen aksè ak aksyon sa a oswa klas sa a.',
    conflict:
      'Adrès sa a deja itilize, oswa chanjman an ta kite klas la san administratè.',
    limited: 'Twòp tantativ. Tann 15 minit anvan ou eseye ankò.',
    previous: 'Anvan',
    next: 'Apre',
    page: 'Paj',
    role: 'Wòl',
    status: 'Estati',
    active: 'Aktif',
    removed: 'Retire',
    member: 'Manm',
    admin: 'Administratè klas',
    staff: 'Pwofesè / pèsonèl',
    guest: 'Envite',
    days: 'Ekspire nan kantite jou sa a',
    maxUses: 'Kantite itilizasyon maksimòm',
    used: 'Itilizasyon',
    expires: 'Ekspire',
    revoke: 'Revoke envitasyon',
    revoked: 'Revoke',
    inviteList: 'Envitasyon yo',
    inviteEmpty: 'Pa gen envitasyon ankò. Envite kamarad klas ou lè ou pare.',
    share: 'Pataje envitasyon sa a',
    once: 'Sove kòd oswa lyen sa a kounye a. Li parèt yon sèl fwa. Pataje l sèlman ak moun ou vle envite.',
    link: 'Lyen envitasyon',
    qr: 'Kòd QR pou lyen envitasyon sa a',
    qrError:
      'Nou pa t kapab kreye kòd QR la. Ou ka toujou itilize lyen envitasyon an.',
    saved: 'Chanjman yo anrejistre.',
    private: 'Espas klas prive',
    schoolNotice:
      'Sa kreye yon espas prive. Sa pa vle di lekòl la verifye l ofisyèlman.',
    noSchools: 'Kreye yon espas lekòl anvan, epi ajoute klas ou k ap gradye a.',
    schoolManage: 'Jere lekòl',
  },
  fr: {
    myClasses: 'Ma classe',
    createSchool: 'Créer un espace école',
    createClass: 'Créer une classe',
    join: 'Rejoindre une classe',
    intro: 'Un lieu où votre classe prend forme.',
    empty:
      'Votre histoire commence ici. Créez un espace école ou rejoignez une classe avec une invitation de votre représentant.',
    school: 'École',
    schoolName: 'Nom de l’école',
    name: 'Nom de la classe',
    slug: 'Adresse courte',
    slugHint:
      'Utilisez des minuscules, chiffres et tirets. L’adresse de classe doit être unique dans son école ; celles des écoles sont uniques sur la plateforme.',
    location: 'Lieu (facultatif)',
    year: 'Année de promotion',
    motto: 'Devise (facultatif)',
    save: 'Enregistrer',
    create: 'Créer',
    back: 'Retour à mes classes',
    manage: 'Gérer',
    members: 'Membres',
    invite: 'Créer une invitation',
    code: 'Code d’invitation',
    joinIntro:
      'Saisissez le code partagé par votre représentant. Votre acceptation explicite est nécessaire pour rejoindre la classe.',
    accept: 'Accepter l’invitation',
    signIn: 'Se connecter pour continuer',
    register: 'Créer un compte',
    returnJoin:
      'Connectez-vous ou inscrivez-vous dans le nouvel onglet, puis revenez accepter votre invitation.',
    loading: 'Chargement…',
    busy: 'Veuillez patienter…',
    error: 'Impossible de terminer cette demande. Veuillez réessayer.',
    retry: 'Réessayer',
    invalid:
      'Vérifiez les informations. L’invitation peut être expirée, révoquée ou entièrement utilisée.',
    denied: 'Vous n’avez pas accès à cette action ou à cette classe.',
    conflict:
      'Cette adresse est déjà utilisée, ou la modification laisserait la classe sans administrateur.',
    limited: 'Trop de tentatives. Attendez 15 minutes avant de réessayer.',
    previous: 'Précédente',
    next: 'Suivante',
    page: 'Page',
    role: 'Rôle',
    status: 'Statut',
    active: 'Actif',
    removed: 'Retiré',
    member: 'Membre',
    admin: 'Administrateur de classe',
    staff: 'Enseignant / personnel',
    guest: 'Invité',
    days: 'Expiration en jours',
    maxUses: 'Utilisations maximales',
    used: 'Utilisations',
    expires: 'Expiration',
    revoke: 'Révoquer l’invitation',
    revoked: 'Révoquée',
    inviteList: 'Invitations',
    inviteEmpty:
      'Aucune invitation pour le moment. Invitez vos camarades quand vous serez prêt.',
    share: 'Partager cette invitation',
    once: 'Conservez ce code ou ce lien maintenant. Il n’apparaît qu’une fois. Partagez-le uniquement avec les personnes à inviter.',
    link: 'Lien d’invitation',
    qr: 'Code QR de ce lien d’invitation',
    qrError:
      'Impossible de générer le code QR. Vous pouvez toujours utiliser le lien.',
    saved: 'Modifications enregistrées.',
    private: 'Espace de classe privé',
    schoolNotice:
      'Vous créez un espace privé. Cela ne constitue pas une vérification officielle par l’école.',
    noSchools: 'Créez d’abord un espace école, puis ajoutez votre promotion.',
    schoolManage: 'Gérer l’école',
  },
  es: {
    myClasses: 'Mi clase',
    createSchool: 'Crear un espacio escolar',
    createClass: 'Crear una clase',
    join: 'Unirse a una clase',
    intro: 'Un lugar donde empieza tu clase.',
    empty:
      'Tu historia empieza aquí. Crea un espacio escolar o únete con una invitación de tu representante.',
    school: 'Escuela',
    schoolName: 'Nombre de la escuela',
    name: 'Nombre de la clase',
    slug: 'Dirección corta',
    slugHint:
      'Usa minúsculas, números y guiones. La dirección de la clase debe ser única en su escuela; las escuelas tienen direcciones únicas en la plataforma.',
    location: 'Ubicación (opcional)',
    year: 'Año de graduación',
    motto: 'Lema (opcional)',
    save: 'Guardar cambios',
    create: 'Crear',
    back: 'Volver a mis clases',
    manage: 'Gestionar',
    members: 'Miembros',
    invite: 'Crear invitación',
    code: 'Código de invitación',
    joinIntro:
      'Introduce el código que compartió tu representante. Debes aceptar explícitamente para unirte.',
    accept: 'Aceptar invitación',
    signIn: 'Inicia sesión para continuar',
    register: 'Crear una cuenta',
    returnJoin:
      'Inicia sesión o regístrate en la nueva pestaña y vuelve aquí para aceptar la invitación.',
    loading: 'Cargando…',
    busy: 'Espera…',
    error: 'No pudimos completar la solicitud. Inténtalo de nuevo.',
    retry: 'Reintentar',
    invalid:
      'Revisa los datos. La invitación puede haber caducado, estar revocada o agotada.',
    denied: 'No tienes acceso a esta acción o clase.',
    conflict:
      'Esta dirección ya está en uso, o el cambio dejaría la clase sin administrador.',
    limited:
      'Demasiados intentos. Espera 15 minutos antes de volver a intentarlo.',
    previous: 'Anterior',
    next: 'Siguiente',
    page: 'Página',
    role: 'Rol',
    status: 'Estado',
    active: 'Activo',
    removed: 'Eliminado',
    member: 'Miembro',
    admin: 'Administrador de clase',
    staff: 'Docente / personal',
    guest: 'Invitado',
    days: 'Caduca en días',
    maxUses: 'Usos máximos',
    used: 'Usos',
    expires: 'Caduca',
    revoke: 'Revocar invitación',
    revoked: 'Revocada',
    inviteList: 'Invitaciones',
    inviteEmpty:
      'Todavía no hay invitaciones. Invita a tus compañeros cuando estés listo.',
    share: 'Compartir esta invitación',
    once: 'Guarda este código o enlace ahora. Solo se muestra una vez. Compártelo únicamente con las personas que quieras invitar.',
    link: 'Enlace de invitación',
    qr: 'Código QR de este enlace de invitación',
    qrError: 'No se pudo generar el código QR. Puedes seguir usando el enlace.',
    saved: 'Cambios guardados.',
    private: 'Espacio privado de clase',
    schoolNotice:
      'Esto crea un espacio privado. No implica una verificación oficial de la escuela.',
    noSchools: 'Crea primero un espacio escolar y luego añade tu clase.',
    schoolManage: 'Gestionar escuela',
  },
};
