import type { Locale } from './identity-copy';
const en = {
  title: 'Review teams',
  security: 'Security and MFA settings',
  accountId: 'Your account ID',
  intro:
    'Shared responsibility, independent approvals, and a backup for every review queue.',
  own: 'Your role grants',
  empty: 'No role grants yet.',
  scope: 'School ID',
  open: 'Open school reviews',
  grants: 'School role grants',
  queues: 'Review queues',
  proposal: 'Propose a role grant',
  recipient: 'Recipient account ID',
  role: 'Role',
  days: 'Expires after (days)',
  propose: 'Send for independent approval',
  approve: 'Approve independently',
  revoke: 'Revoke grant',
  reason: 'Decision reason',
  password: 'Confirm your password',
  code: 'Authenticator or recovery code',
  proof:
    'Each change requires your password and a fresh second factor. Approval must come from a different administrator who is not the recipient.',
  queue: 'Configure a review queue',
  name: 'Queue name',
  primary: 'Primary reviewer grant ID',
  backup: 'Backup reviewer grant ID',
  create: 'Create queue',
  update: 'Save assignment',
  covered: 'Primary and backup authorized',
  uncovered: 'Coverage needs attention',
  primaryMissing: 'Primary reviewer authorization unavailable',
  backupMissing: 'Backup reviewer authorization unavailable',
  coverage:
    'Coverage checks account and role eligibility. It does not mean someone is online or on call.',
  boundary:
    'These screens configure review teams. Consent cases, evidence review, appeals, and privacy fulfillment are not available yet.',
  next: 'Next page',
  previous: 'Previous page',
  refresh: 'Refresh',
  expires: 'Expires',
  requested: 'Awaiting independent approval',
  active: 'Active',
  expired: 'Expired',
  revoked: 'Revoked',
  conflict:
    'The record changed or the selected reviewers are no longer eligible. Refresh and review the latest configuration before retrying.',
  denied:
    'Sign in with MFA and check your school-scoped permissions. Your password or second factor may also need to be re-entered.',
  queueManager: 'Queue manager',
  consent: 'Participation reviewer',
  safeguarding: 'Safeguarding reviewer',
  privacy: 'Privacy reviewer',
  auditor: 'Auditor',
};
type Copy = typeof en;
export const governanceCopy: Record<Locale, Copy> = {
  en,
  fr: {
    title: 'Équipes de révision',
    security: 'Sécurité et paramètres MFA',
    accountId: 'Identifiant de votre compte',
    intro:
      'Responsabilités partagées, approbations indépendantes et un suppléant pour chaque file.',
    own: 'Vos attributions de rôles',
    empty: 'Aucun rôle attribué.',
    scope: 'Identifiant de l’établissement',
    open: 'Ouvrir les révisions',
    grants: 'Rôles de l’établissement',
    queues: 'Files de révision',
    proposal: 'Proposer un rôle',
    recipient: 'Identifiant du compte bénéficiaire',
    role: 'Rôle',
    days: 'Expiration (jours)',
    propose: 'Demander une approbation indépendante',
    approve: 'Approuver indépendamment',
    revoke: 'Révoquer le rôle',
    reason: 'Motif de la décision',
    password: 'Confirmez votre mot de passe',
    code: 'Code authentificateur ou de récupération',
    proof:
      'Chaque modification exige votre mot de passe et un nouveau second facteur. Un autre administrateur, différent du bénéficiaire, doit approuver.',
    queue: 'Configurer une file de révision',
    name: 'Nom de la file',
    primary: 'Identifiant du rôle du titulaire',
    backup: 'Identifiant du rôle du suppléant',
    create: 'Créer la file',
    update: 'Enregistrer l’affectation',
    covered: 'Titulaire et suppléant autorisés',
    uncovered: 'Couverture à vérifier',
    primaryMissing: 'Autorisation du titulaire indisponible',
    backupMissing: 'Autorisation du suppléant indisponible',
    coverage:
      'La couverture vérifie les comptes et les rôles. Elle ne signifie pas que quelqu’un est en ligne ou de permanence.',
    boundary:
      'Ces écrans configurent les équipes. Les dossiers de consentement, les preuves, les appels et les demandes de confidentialité ne sont pas encore disponibles.',
    next: 'Page suivante',
    previous: 'Page précédente',
    refresh: 'Actualiser',
    expires: 'Expiration',
    requested: 'Approbation indépendante en attente',
    active: 'Actif',
    expired: 'Expiré',
    revoked: 'Révoqué',
    conflict:
      'Le dossier a changé ou les responsables choisis ne sont plus éligibles. Actualisez et vérifiez la configuration avant de réessayer.',
    denied:
      'Connectez-vous avec MFA et vérifiez vos droits pour cet établissement. Vous devrez peut-être ressaisir le mot de passe ou le second facteur.',
    queueManager: 'Responsable des files',
    consent: 'Réviseur de participation',
    safeguarding: 'Réviseur de protection',
    privacy: 'Réviseur de confidentialité',
    auditor: 'Auditeur',
  },
  ht: {
    title: 'Ekip revizyon',
    security: 'Sekirite ak paramèt MFA',
    accountId: 'Idantifyan kont ou',
    intro:
      'Responsablite pataje, apwobasyon endepandan ak yon ranplasan pou chak lis revizyon.',
    own: 'Wòl yo ba ou',
    empty: 'Ou poko gen wòl.',
    scope: 'Idantifyan lekòl la',
    open: 'Louvri revizyon lekòl la',
    grants: 'Wòl lekòl la',
    queues: 'Lis revizyon',
    proposal: 'Pwopoze yon wòl',
    recipient: 'Idantifyan kont moun nan',
    role: 'Wòl',
    days: 'Ekspirasyon (jou)',
    propose: 'Mande apwobasyon endepandan',
    approve: 'Apwouve endepandamman',
    revoke: 'Retire wòl la',
    reason: 'Rezon desizyon an',
    password: 'Konfime modpas ou',
    code: 'Kòd otantifikatè oswa rekiperasyon',
    proof:
      'Chak chanjman mande modpas ou ak yon nouvo dezyèm faktè. Yon lòt administratè ki pa moun k ap resevwa wòl la dwe apwouve.',
    queue: 'Konfigire yon lis revizyon',
    name: 'Non lis la',
    primary: 'Idantifyan wòl responsab prensipal la',
    backup: 'Idantifyan wòl ranplasan an',
    create: 'Kreye lis la',
    update: 'Anrejistre responsab yo',
    covered: 'Prensipal ak ranplasan otorize',
    uncovered: 'Kouvèti bezwen atansyon',
    primaryMissing: 'Responsab prensipal la pa gen otorizasyon disponib',
    backupMissing: 'Ranplasan an pa gen otorizasyon disponib',
    coverage:
      'Kouvèti verifye kont ak wòl yo. Sa pa vle di yon moun sou entènèt oswa an sèvis.',
    boundary:
      'Ekran sa yo konfigire ekip yo. Dosye konsantman, prèv, apèl ak demann vi prive poko disponib.',
    next: 'Paj apre',
    previous: 'Paj anvan',
    refresh: 'Rafrechi',
    expires: 'Ekspirasyon',
    requested: 'Ap tann apwobasyon endepandan',
    active: 'Aktif',
    expired: 'Ekspire',
    revoked: 'Retire',
    conflict:
      'Dosye a chanje oswa responsab yo pa kalifye ankò. Rafrechi epi verifye konfigirasyon an anvan ou eseye ankò.',
    denied:
      'Konekte ak MFA epi verifye dwa ou pou lekòl sa a. Ou ka bezwen antre modpas oswa dezyèm faktè a ankò.',
    queueManager: 'Responsab lis yo',
    consent: 'Revizè patisipasyon',
    safeguarding: 'Revizè pwoteksyon',
    privacy: 'Revizè vi prive',
    auditor: 'Oditè',
  },
  es: {
    title: 'Equipos de revisión',
    security: 'Seguridad y configuración MFA',
    accountId: 'Identificador de tu cuenta',
    intro:
      'Responsabilidad compartida, aprobaciones independientes y un suplente por cada cola.',
    own: 'Tus asignaciones de roles',
    empty: 'Todavía no hay roles asignados.',
    scope: 'Identificador de la institución',
    open: 'Abrir revisiones',
    grants: 'Roles de la institución',
    queues: 'Colas de revisión',
    proposal: 'Proponer un rol',
    recipient: 'Identificador de la cuenta destinataria',
    role: 'Rol',
    days: 'Caduca después de (días)',
    propose: 'Solicitar aprobación independiente',
    approve: 'Aprobar independientemente',
    revoke: 'Revocar rol',
    reason: 'Motivo de la decisión',
    password: 'Confirma tu contraseña',
    code: 'Código de autenticación o recuperación',
    proof:
      'Cada cambio requiere tu contraseña y un segundo factor nuevo. Debe aprobar otro administrador que no sea el destinatario.',
    queue: 'Configurar una cola',
    name: 'Nombre de la cola',
    primary: 'Identificador del rol del revisor principal',
    backup: 'Identificador del rol del suplente',
    create: 'Crear cola',
    update: 'Guardar asignación',
    covered: 'Principal y suplente autorizados',
    uncovered: 'La cobertura necesita atención',
    primaryMissing: 'Autorización del principal no disponible',
    backupMissing: 'Autorización del suplente no disponible',
    coverage:
      'La cobertura comprueba cuentas y roles. No indica presencia en línea ni disponibilidad de guardia.',
    boundary:
      'Estas pantallas configuran equipos. Los casos de consentimiento, pruebas, apelaciones y solicitudes de privacidad aún no están disponibles.',
    next: 'Página siguiente',
    previous: 'Página anterior',
    refresh: 'Actualizar',
    expires: 'Caducidad',
    requested: 'Pendiente de aprobación independiente',
    active: 'Activo',
    expired: 'Caducado',
    revoked: 'Revocado',
    conflict:
      'El registro cambió o los revisores ya no cumplen los requisitos. Actualiza y revisa la configuración antes de reintentar.',
    denied:
      'Inicia sesión con MFA y comprueba tus permisos para esta institución. Puede que debas volver a introducir la contraseña o el segundo factor.',
    queueManager: 'Gestor de colas',
    consent: 'Revisor de participación',
    safeguarding: 'Revisor de protección',
    privacy: 'Revisor de privacidad',
    auditor: 'Auditor',
  },
};
