import type { Locale } from './identity-copy';
const en = {
  dashboard: 'Class dashboard',
  classNavigation: 'Class navigation',
  overview: 'Overview',
  yourPage: 'Your yearbook page',
  contribute: 'A little of you, for everyone to remember.',
  contribution:
    'Add your photo, a few words, and the things that made these years yours.',
  yearbook: 'Yearbook',
  preview: 'Read the preview',
  edit: 'Edit the yearbook',
  draft: 'Draft edition',
  draftNote:
    'This preview changes as your class contributes. It has not been published.',
  progress: 'The edition is taking shape',
  profiles: 'Profiles started',
  photos: 'Graduation photos',
  quotes: 'Personal quotes',
  members: 'Class members',
  manage: 'Members & invitations',
  manageNote: 'Invite your classmates and manage access.',
  editNote: 'Arrange the pages, add your class photo, and set the tone.',
  profileTitle: 'A page that feels like you.',
  profileIntro:
    'Only your name is required. Share what you want your classmates to remember.',
  name: 'Display name',
  nickname: 'Nickname',
  bio: 'Short biography',
  quote: 'Your quote',
  activities: 'Activities & interests',
  aspiration: 'What comes next',
  contact: 'Contact or social details',
  optional: 'Optional',
  privacy: 'Who can see your page?',
  private: 'Only me',
  shared: 'My class',
  privacyNote:
    'Choose My class to include your page in the draft yearbook. You can change this before publication.',
  contactPrivacy: 'Who can see your contact details?',
  contactNote: 'Contact details never appear in the yearbook.',
  save: 'Save changes',
  savePreview: 'Save & preview',
  saved: 'Changes saved.',
  saving: 'Saving…',
  conflict:
    'Someone saved a newer version. Your edits are still here. Copy anything you need, then reload the latest version.',
  reload: 'Reload latest version',
  photo: 'Graduation photo',
  upload: 'Choose a photo',
  alt: 'Describe this photo',
  imageHelp:
    'JPEG, PNG or WebP · up to 8 MB · at least 128 × 128 pixels. Photos are private until you share your page.',
  uploading: 'Checking and uploading your photo…',
  uploaded: 'Photo uploaded. Save your changes to add it to the page.',
  badImage:
    'This photo could not be accepted. Use a still JPEG, PNG or WebP between 128 pixels and 16 megapixels, up to 8 MB.',
  removePhoto: 'Delete photo',
  removeConfirm: 'Delete this photo permanently?',
  cancel: 'Cancel',
  unavailable: 'This profile is private or unavailable.',
  noPhoto: 'No photo yet',
  title: 'Edition title',
  theme: 'Paper & color',
  PAPER: 'Terracotta',
  INK: 'Deep ink',
  GARDEN: 'Garden green',
  sections: 'Pages & sections',
  addSection: 'Add a section',
  sectionType: 'Section type',
  sectionTitle: 'Section title',
  body: 'Words for this page',
  remove: 'Remove section',
  up: 'Move up',
  down: 'Move down',
  gallery: 'Section photos',
  removeImage: 'Remove from section',
  contents: 'In this edition',
  empty: 'Your class is still gathering its first pages.',
  emptyMembers: 'No shared profiles on this page yet.',
  start: 'Start with your own page',
  editorNote:
    'Changes stay in the draft. Preview the edition whenever you want.',
  memberNote: 'These pages use the profiles classmates choose to share.',
  COVER: 'Cover',
  MESSAGE: 'Class message',
  CLASS_PHOTO: 'Class photo',
  MEMBERS: 'Member pages',
  STAFF: 'Teacher & staff pages',
  QUOTES: 'Memorable quotes',
  GALLERY: 'Gallery',
  ACKNOWLEDGEMENTS: 'Acknowledgements',
  GRADUATION: 'Graduation details',
  back: 'Back to class',
  invitation: 'Invite classmates',
  yourProfile: 'Edit your page',
  imageUnavailable: 'Photo unavailable. Try reloading.',
};
type Copy = { [K in keyof typeof en]: string };
export const yearbookCopy: Record<Locale, Copy> = {
  en,
  fr: {
    dashboard: 'Tableau de bord de la classe',
    classNavigation: 'Navigation de la classe',
    overview: 'Vue d’ensemble',
    yourPage: 'Votre page de promotion',
    contribute: 'Un peu de vous, pour ne rien oublier.',
    contribution:
      'Votre photo, quelques mots et ce qui a rendu ces années uniques.',
    yearbook: 'Album de promotion',
    preview: 'Lire l’aperçu',
    edit: 'Composer l’album',
    draft: 'Édition en préparation',
    draftNote:
      'Cet aperçu évolue avec les contributions de la classe. Il n’a pas encore été publié.',
    progress: 'L’édition prend forme',
    profiles: 'Profils commencés',
    photos: 'Photos de fin d’études',
    quotes: 'Citations personnelles',
    members: 'Membres de la classe',
    manage: 'Membres et invitations',
    manageNote: 'Invitez vos camarades et gérez les accès.',
    editNote:
      'Organisez les pages, ajoutez la photo de classe et donnez le ton.',
    profileTitle: 'Une page à votre image.',
    profileIntro:
      'Seul votre nom est obligatoire. Partagez ce que vous souhaitez laisser en souvenir.',
    name: 'Nom affiché',
    nickname: 'Surnom',
    bio: 'Courte biographie',
    quote: 'Votre citation',
    activities: 'Activités et centres d’intérêt',
    aspiration: 'Et après ?',
    contact: 'Coordonnées ou réseaux sociaux',
    optional: 'Facultatif',
    privacy: 'Qui peut voir votre page ?',
    private: 'Moi uniquement',
    shared: 'Ma classe',
    privacyNote:
      'Choisissez Ma classe pour inclure votre page dans l’aperçu de l’album. Vous pouvez changer ce choix avant la publication.',
    contactPrivacy: 'Qui peut voir vos coordonnées ?',
    contactNote: 'Les coordonnées ne figurent jamais dans l’album.',
    save: 'Enregistrer',
    savePreview: 'Enregistrer et voir l’aperçu',
    saved: 'Modifications enregistrées.',
    saving: 'Enregistrement…',
    conflict:
      'Une version plus récente a été enregistrée. Vos modifications sont encore ici. Copiez ce que vous souhaitez garder, puis rechargez la dernière version.',
    reload: 'Recharger la dernière version',
    photo: 'Photo de fin d’études',
    upload: 'Choisir une photo',
    alt: 'Décrivez cette photo',
    imageHelp:
      'JPEG, PNG ou WebP · 8 Mo maximum · au moins 128 × 128 pixels. La photo reste privée tant que votre page l’est.',
    uploading: 'Vérification et envoi de votre photo…',
    uploaded: 'Photo envoyée. Enregistrez pour l’ajouter à votre page.',
    badImage:
      'Cette photo ne peut pas être utilisée. Choisissez une image fixe JPEG, PNG ou WebP de 128 pixels à 16 mégapixels, de 8 Mo maximum.',
    removePhoto: 'Supprimer la photo',
    removeConfirm: 'Supprimer définitivement cette photo ?',
    cancel: 'Annuler',
    unavailable: 'Ce profil est privé ou indisponible.',
    noPhoto: 'Pas encore de photo',
    title: 'Titre de l’édition',
    theme: 'Papier et couleur',
    PAPER: 'Terre cuite',
    INK: 'Encre profonde',
    GARDEN: 'Vert jardin',
    sections: 'Pages et rubriques',
    addSection: 'Ajouter une rubrique',
    sectionType: 'Type de rubrique',
    sectionTitle: 'Titre de la rubrique',
    body: 'Texte de cette page',
    remove: 'Retirer la rubrique',
    up: 'Monter',
    down: 'Descendre',
    gallery: 'Photos de la rubrique',
    removeImage: 'Retirer de la rubrique',
    contents: 'Dans cette édition',
    empty: 'Votre classe rassemble ses premières pages.',
    emptyMembers: 'Aucun profil partagé sur cette page pour le moment.',
    start: 'Commencez par votre page',
    editorNote:
      'Les modifications restent dans le brouillon. Consultez l’aperçu à tout moment.',
    memberNote:
      'Ces pages reprennent les profils que vos camarades choisissent de partager.',
    COVER: 'Couverture',
    MESSAGE: 'Message de la classe',
    CLASS_PHOTO: 'Photo de classe',
    MEMBERS: 'Pages des membres',
    STAFF: 'Pages des enseignants et du personnel',
    QUOTES: 'Citations mémorables',
    GALLERY: 'Galerie',
    ACKNOWLEDGEMENTS: 'Remerciements',
    GRADUATION: 'Détails de la cérémonie',
    back: 'Retour à la classe',
    invitation: 'Inviter des camarades',
    yourProfile: 'Modifier votre page',
    imageUnavailable: 'Photo indisponible. Essayez de recharger.',
  },
  ht: {
    dashboard: 'Tablo jesyon klas la',
    classNavigation: 'Navigasyon klas la',
    overview: 'Apèsi',
    yourPage: 'Paj ou nan albòm nan',
    contribute: 'Yon ti moso nan ou, pou nou sonje.',
    contribution: 'Foto ou, kèk mo, ak sa ki te fè ane sa yo espesyal pou ou.',
    yearbook: 'Albòm pwomosyon',
    preview: 'Li apèsi a',
    edit: 'Prepare albòm nan',
    draft: 'Edisyon an preparasyon',
    draftNote:
      'Apèsi sa a chanje pandan klas la ap kontribye. Li poko pibliye.',
    progress: 'Edisyon an ap pran fòm',
    profiles: 'Pwofil ki kòmanse',
    photos: 'Foto gradyasyon',
    quotes: 'Sitasyon pèsonèl',
    members: 'Manm klas la',
    manage: 'Manm ak envitasyon',
    manageNote: 'Envite kamarad ou yo epi jere aksè yo.',
    editNote: 'Ranje paj yo, ajoute foto klas la epi bay albòm nan koulè li.',
    profileTitle: 'Yon paj ki sanble avè w.',
    profileIntro:
      'Se non ou sèlman ki obligatwa. Pataje sa ou vle kamarad ou yo sonje.',
    name: 'Non ki parèt',
    nickname: 'Ti non',
    bio: 'Ti biyografi',
    quote: 'Sitasyon ou',
    activities: 'Aktivite ak enterè',
    aspiration: 'Sa ki vini apre',
    contact: 'Kontak oswa rezo sosyal',
    optional: 'Si ou vle',
    privacy: 'Kiyès ki ka wè paj ou a?',
    private: 'Mwen sèlman',
    shared: 'Klas mwen',
    privacyNote:
      'Chwazi Klas mwen pou mete paj ou nan apèsi albòm nan. Ou ka chanje sa anvan piblikasyon.',
    contactPrivacy: 'Kiyès ki ka wè kontak ou?',
    contactNote: 'Kontak yo pa janm parèt nan albòm nan.',
    save: 'Anrejistre',
    savePreview: 'Anrejistre epi wè apèsi a',
    saved: 'Chanjman yo anrejistre.',
    saving: 'N ap anrejistre…',
    conflict:
      'Yon vèsyon pi resan anrejistre. Chanjman ou yo toujou la. Kopye sa ou bezwen, apre sa rechaje dènye vèsyon an.',
    reload: 'Rechaje dènye vèsyon an',
    photo: 'Foto gradyasyon',
    upload: 'Chwazi yon foto',
    alt: 'Dekri foto sa a',
    imageHelp:
      'JPEG, PNG oswa WebP · jiska 8 MB · omwen 128 × 128 piksèl. Foto a rete prive jiskaske ou pataje paj ou.',
    uploading: 'N ap verifye epi voye foto ou…',
    uploaded: 'Foto a voye. Anrejistre chanjman yo pou ajoute l nan paj la.',
    badImage:
      'Nou pa ka itilize foto sa a. Chwazi yon foto fiks JPEG, PNG oswa WebP ant 128 piksèl ak 16 megapiksèl, jiska 8 MB.',
    removePhoto: 'Efase foto a',
    removeConfirm: 'Efase foto sa a nèt?',
    cancel: 'Anile',
    unavailable: 'Pwofil sa a prive oswa li pa disponib.',
    noPhoto: 'Poko gen foto',
    title: 'Tit edisyon an',
    theme: 'Papye ak koulè',
    PAPER: 'Tè kwit',
    INK: 'Lank fonse',
    GARDEN: 'Vèt jaden',
    sections: 'Paj ak seksyon',
    addSection: 'Ajoute yon seksyon',
    sectionType: 'Kalite seksyon',
    sectionTitle: 'Tit seksyon an',
    body: 'Tèks paj sa a',
    remove: 'Retire seksyon an',
    up: 'Monte',
    down: 'Desann',
    gallery: 'Foto seksyon an',
    removeImage: 'Retire nan seksyon an',
    contents: 'Nan edisyon sa a',
    empty: 'Klas ou ap rasanble premye paj li yo.',
    emptyMembers: 'Poko gen pwofil pataje sou paj sa a.',
    start: 'Kòmanse ak paj pa ou',
    editorNote: 'Chanjman yo rete nan bouyon an. Ou ka gade apèsi a nenpòt lè.',
    memberNote: 'Paj sa yo sèvi ak pwofil kamarad yo chwazi pataje.',
    COVER: 'Kouvèti',
    MESSAGE: 'Mesaj klas la',
    CLASS_PHOTO: 'Foto klas la',
    MEMBERS: 'Paj manm yo',
    STAFF: 'Paj pwofesè ak pèsonèl',
    QUOTES: 'Sitasyon memorab',
    GALLERY: 'Galri',
    ACKNOWLEDGEMENTS: 'Remèsiman',
    GRADUATION: 'Detay gradyasyon',
    back: 'Retounen nan klas la',
    invitation: 'Envite kamarad',
    yourProfile: 'Modifye paj ou',
    imageUnavailable: 'Foto a pa disponib. Eseye rechaje.',
  },
  es: {
    dashboard: 'Panel de la clase',
    classNavigation: 'Navegación de la clase',
    overview: 'Resumen',
    yourPage: 'Tu página del anuario',
    contribute: 'Un poco de ti, para recordar siempre.',
    contribution: 'Tu foto, unas palabras y lo que hizo tuyos estos años.',
    yearbook: 'Anuario',
    preview: 'Leer la vista previa',
    edit: 'Editar el anuario',
    draft: 'Edición en preparación',
    draftNote:
      'Esta vista previa cambia con las aportaciones de la clase. Todavía no se ha publicado.',
    progress: 'La edición toma forma',
    profiles: 'Perfiles iniciados',
    photos: 'Fotos de graduación',
    quotes: 'Citas personales',
    members: 'Miembros de la clase',
    manage: 'Miembros e invitaciones',
    manageNote: 'Invita a tus compañeros y gestiona el acceso.',
    editNote:
      'Organiza las páginas, añade la foto de clase y define el estilo.',
    profileTitle: 'Una página que habla de ti.',
    profileIntro:
      'Solo tu nombre es obligatorio. Comparte lo que quieras dejar como recuerdo.',
    name: 'Nombre visible',
    nickname: 'Apodo',
    bio: 'Biografía breve',
    quote: 'Tu cita',
    activities: 'Actividades e intereses',
    aspiration: 'Lo que viene después',
    contact: 'Contacto o redes sociales',
    optional: 'Opcional',
    privacy: '¿Quién puede ver tu página?',
    private: 'Solo yo',
    shared: 'Mi clase',
    privacyNote:
      'Elige Mi clase para incluir tu página en la vista previa del anuario. Puedes cambiarlo antes de la publicación.',
    contactPrivacy: '¿Quién puede ver tus datos de contacto?',
    contactNote: 'Los datos de contacto nunca aparecen en el anuario.',
    save: 'Guardar cambios',
    savePreview: 'Guardar y ver la vista previa',
    saved: 'Cambios guardados.',
    saving: 'Guardando…',
    conflict:
      'Se ha guardado una versión más reciente. Tus cambios siguen aquí. Copia lo que necesites y carga la última versión.',
    reload: 'Cargar la última versión',
    photo: 'Foto de graduación',
    upload: 'Elegir una foto',
    alt: 'Describe esta foto',
    imageHelp:
      'JPEG, PNG o WebP · hasta 8 MB · al menos 128 × 128 píxeles. La foto es privada hasta que compartas tu página.',
    uploading: 'Comprobando y subiendo tu foto…',
    uploaded: 'Foto subida. Guarda los cambios para añadirla a tu página.',
    badImage:
      'No se puede usar esta foto. Elige una imagen fija JPEG, PNG o WebP entre 128 píxeles y 16 megapíxeles, de hasta 8 MB.',
    removePhoto: 'Eliminar foto',
    removeConfirm: '¿Eliminar esta foto permanentemente?',
    cancel: 'Cancelar',
    unavailable: 'Este perfil es privado o no está disponible.',
    noPhoto: 'Aún no hay foto',
    title: 'Título de la edición',
    theme: 'Papel y color',
    PAPER: 'Terracota',
    INK: 'Tinta profunda',
    GARDEN: 'Verde jardín',
    sections: 'Páginas y secciones',
    addSection: 'Añadir una sección',
    sectionType: 'Tipo de sección',
    sectionTitle: 'Título de la sección',
    body: 'Texto de esta página',
    remove: 'Quitar sección',
    up: 'Subir',
    down: 'Bajar',
    gallery: 'Fotos de la sección',
    removeImage: 'Quitar de la sección',
    contents: 'En esta edición',
    empty: 'Tu clase está reuniendo sus primeras páginas.',
    emptyMembers: 'Aún no hay perfiles compartidos en esta página.',
    start: 'Empieza con tu página',
    editorNote:
      'Los cambios quedan en el borrador. Puedes consultar la vista previa cuando quieras.',
    memberNote:
      'Estas páginas usan los perfiles que tus compañeros eligen compartir.',
    COVER: 'Portada',
    MESSAGE: 'Mensaje de la clase',
    CLASS_PHOTO: 'Foto de clase',
    MEMBERS: 'Páginas de miembros',
    STAFF: 'Páginas de docentes y personal',
    QUOTES: 'Citas memorables',
    GALLERY: 'Galería',
    ACKNOWLEDGEMENTS: 'Agradecimientos',
    GRADUATION: 'Detalles de graduación',
    back: 'Volver a la clase',
    invitation: 'Invitar compañeros',
    yourProfile: 'Editar tu página',
    imageUnavailable: 'Foto no disponible. Intenta recargar.',
  },
};
