ALTER TABLE "Session" ADD COLUMN "id" UUID NOT NULL DEFAULT gen_random_uuid();
ALTER TABLE "Session" ADD COLUMN "lastSeenAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
CREATE UNIQUE INDEX "Session_id_key" ON "Session"("id");
ALTER TABLE "School" ADD COLUMN "verifiedAt" TIMESTAMPTZ(3);
ALTER TYPE "MediaStatus" ADD VALUE 'PROCESSING';
ALTER TABLE "MediaAsset" ADD COLUMN "purgedAt" TIMESTAMPTZ(3);
